<?php

namespace ComparateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComparateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComparateurRepository extends EntityRepository //execute les fonctions dql
{
   public function getResultsByCity($destinations, $typeCereales){
       $qb = $this->createQueryBuilder("cereales");


       $qb->select("cereales")
           ->where("cereales.destination = :destinations")
           ->andWhere("cereales.produit = :typeCereales")
           ->setParameter("destinations", $destinations)
           ->setParameter("typeCereales", $typeCereales);


       $resultats = $qb->getQuery()->getResult();

        return $resultats;
   }


}
