<?php

namespace ComparateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComparateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComparateurRepository extends EntityRepository
{
}
