ComparateurBundle\Entity\Comparateur:
    type: entity
    table: null
    repositoryClass: ComparateurBundle\Repository\ComparateurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        entreprise:
             type: string
             length: 255
        produit:
            type: string
            length: 255
        destination:
            type: string
            length: 255
        prix:
            type: integer
        proteines:
            type: integer
        humidite:
            type: integer
        ps:
            type: integer
        hagberg:
            type: integer
    lifecycleCallbacks: {  }
