comparateur_comparateur:
    resource: "@ComparateurBundle/Resources/config/routing/comparateur.yml"
    prefix:   /comparateur

comparateur_homepage:
    path:     /
    defaults: { _controller: ComparateurBundle:Default:index }

comparateur_test:
    path:     /fraisdeportrouen
    defaults: { _controller: ComparateurBundle:Comparateur:setFraisDePorts }

page_resultats:
    path:     /resultats
    defaults: { _controller: ComparateurBundle:Comparateur:setFraisDePorts }
